### ISSUE TITLE
[Engine] Runtime Error OpenAL

### ISSUE THREAD

**Issue by persn** [tzachshabtay/MonoAGS#138]
I got some exceptions trying to run the demo game on my computer, Windows 10. From the exception messages I was able to derive that I was missing the [OpenAL SDK](https://openal.org/) and installing it fixed it, but this should probably be included in the Readme.

**Comment by tzachshabtay** [comment]
Yes, you're right. I actually intend to fix it by including OpenAL Soft dll directly in the engine so you wouldn't need to install OpenAL, I'm planning to add it in the next few days.

**Comment by persn** [comment]
That sounds like a good plan
