### ISSUE TITLE
Suggestion for "Moving areas" showcase

### ISSUE THREAD

**Issue by ivan-mogilko** [tzachshabtay/MonoAGS#167]
There is this feature showcase that demonstrates moving areas.

That's tad confusing that showcase switches character's connection to the area, only noting this fact in the label above. To be honest, at first I thought there is a bug in the engine, and even started to write a ticket here :).

May I suggest make it a checkbox for user to toggle instead? Also, when checked back, should character be placed on area if it's currently not standing on it?

I also noticed couple of issues:
* sometimes label sais "moving and rotating character and area together", while it continues to only move them.
* it's actually possible to walk past the visible area's border a little.

**Comment by tzachshabtay** [comment]
Yes for the checkbox 👍 

> sometimes label sais "moving and rotating character and area together", while it continues to only move them.

Arrrm, there is no "moving and rotating" together, it's either moving or rotating? 🤔 

> it's actually possible to walk past the visible area's border a little.

Well, yes, that's because the anchor point of the character is (0.5, 0), so the walk area is restricting the center point on the character (horizontally). I believe that is how it works in AGS too.
I considered "cheating" by adding a border to the area, this will look nicer but might be misleading. Not sure if there's a better way to show it.

**Comment by ivan-mogilko** [comment]
> Arrrm, there is no "moving and rotating" together, it's either moving or rotating? :thinking:

Hmm, yes, I typed something wrong. What happens is that sometimes it changes to "rotating...", but continues to move. Also sometimes it switches the label text for a very small duration and then switches to something different.

**Comment by tzachshabtay** [comment]
Hmm, I'm not seeing that.
Is there something specific you do to reproduce that?
(A screen recording would be great if you have the time).

**Comment by ivan-mogilko** [comment]
I think I got it, it happens if you open "Moving Areas" demo, then switch to another, then back.
After you do, label text and area movement seem to desync.

Video (2 MB): https://www.dropbox.com/s/o4i8edtre6yqc5b/MonoAGS%20-%20Moving%20Areas%20Demo%20issue.avi?dl=0
