### ISSUE TITLE
Object scaling works incorrectly with Anchor?

### ISSUE THREAD

**Issue by ivan-mogilko** [tzachshabtay/MonoAGS#169]
It seems to me that the scaling operation treats image's Anchor incorrectly, at least for room objects.

Description of an anchor sais: "The units of the anchor point is in relation for the image size, where (0f,0f) is the bottom-left corner, and (1f,1f) is the top-right corner.", which means (0.5f, 0.5f) is the center of image. That makes perfect sense.

However, setting scaling to object produces unexpected results.

For example: with default anchor (0.5, 0), scaling an object horizontally makes its image appear shifted to the left, proportionally to the scale value, while normally I'd think it stays centered to the same position in the room.
If I set Anchor as (0, 0), scaled object stays on same place.

**Comment by tzachshabtay** [comment]
I reproduced this, definitely a bug, it used to work, and I probably broke something in recent commits. I'll work on it soon.

**Comment by tzachshabtay** [comment]
@ivan-mogilko should work now, let me know if it matches what you expect.
