### ISSUE TITLE
Extract Sprite to its own component

### ISSUE THREAD

**Issue by tzachshabtay** [tzachshabtay/MonoAGS#206]
Extract Sprite from the animation component to its own component. The animation component will have a dependency on the Sprite component and will set the Sprite through it.

**Comment by ivan-mogilko** [comment]
Does this assume moving Border and DebugDrawPivot to Sprite component?

**Comment by tzachshabtay** [comment]
I'm not sure if we want to have the border in the sprite or in a separate border component. Separate component might make more sense as we'll be able to give borders for custom renderers which are not sprites.
As for DebugDrawPivot, I want to eventually completely replace it with #81 , which I guess we'll also implement as a custom renderer in a separate component.

**Comment by ivan-mogilko** [comment]
What I mean is, since we were talking about some minor refactoring, that would make renderers use SpriteComponent's contents instead of AnimationComponent, I could move these two properties into SpriteComponent as the first step.

**Comment by tzachshabtay** [comment]
Sure, it's up to you.

**Comment by tzachshabtay** [comment]
Resolved by #211
