### ISSUE TITLE
Walk-behinds not redrawn when room animation frame changes

### ISSUE THREAD

**Issue by tzachshabtay** [tzachshabtay/MonoAGS#252]
This is a regression from when the display list was refactored. The walk-behinds map only sets the walk-behind image when the display list changes and the display list doesn't refresh when animation frame changes (unless the Z changes with that).
Should fix by setting the walk-behind image when the room animation frame changes, regardless of the display list.

**Comment by ivan-mogilko** [comment]
Sorry if a stupid question (also not directly relevant) but why does monoags support walk-behind masks at all? Is not it much easier for everyone to just make room of several layers? With separate images you have much better control over shape too, with masks you need to keep it updated with room gfx all the time.
