### ISSUE TITLE
The purpose of walk-behinds

### ISSUE THREAD

**Issue by ivan-mogilko** [tzachshabtay/MonoAGS#253]
I wanted to ask, what is the purpose of supporting walk-behind masks in MonoAGS?
Is not it much easier for everyone to just make room of several layers? With separate images you have much better control over shape too (at design time), with masks you need to keep it updated with room gfx all the time.

Walk-behinds seem to be a legacy of engines based on software-rendering where pixel masks could optimize perfomance and save disk space a bit, but it's hard to tell if any of that is relevant to modern day games.

Mask could be slightly advantageous when you have an editor tool to quickly paint it over, but in the abscence of one it becomes even more complicated compared to having a distinct image of room layer.

So, frankly, I was very surprised to see walk-behind mask support in MonoAGS. IMHO this is something that makes sense to add only when main features are complete and a well-sized group of game developers ask for such feature.

**PS.** We could ask around on AGS forums to know if there is any actual benefit of these from artist's perspective, but frankly it seems to me this is rather a question of approach and getting used to a tool.

**Comment by tzachshabtay** [comment]
I agree that walk-behinds are not a must-have feature, but, as we will have an editor tool for drawing areas, it can be more convenient (like you said yourself), especially in scenarios where you didn't draw the background with layers in mind (or maybe you downloaded it from somewhere, or maybe you're porting an existing AGS game, or maybe it's just placeholder art but you want to quickly feel out the spaces within).
