### ISSUE TITLE
Win builds problem

### ISSUE THREAD

**Issue by necros2k7** [tzachshabtay/MonoAGS#320]
subj

**Comment by tzachshabtay** [comment]
Reran the windows build and it seems to be passing: https://ci.appveyor.com/project/tzachshabtay/monoags/builds/38167315/job/hebud37655sybyeo

Let me know if you have any specific issues I can help with.

**Comment by necros2k7** [comment]
Ehh, by your link it says build failed and no arifacts present

**Comment by tzachshabtay** [comment]
Added artifacts to the build: https://ci.appveyor.com/project/tzachshabtay/monoags/build/job/dc3k0wwumw9atc0k/artifacts

**Comment by necros2k7** [comment]
Engine folder have no exe inside only dlls is it ok?

**Comment by tzachshabtay** [comment]
Yeah, the engine itself is a library, not an executable. The game is the executable and it imports the engine library (see the demo game for an example).
